### ISSUE TITLE
Question about calculating similarity

### ISSUE THREAD

**Issue by xiazl5515** [YueYongDev/zhai#1]
The lexicon of the two articles is too small, so the frequency values in the tfidf matrix calculated by this very very small corpus are not suitable for simple cosine similarity metrics, that is, they cannot reflect the similarity of the two articles in the field of performance culture. It will also be limited by the inevitable domain-specific words in the two papers themselves. (In fact, I tend to use my own built-in stop word list in any professional field). You can try to add a few papers after tf-idf and then look at the similarities between the two articles.

**Comment by YueYongDev** [comment]
In this article, I only use the TF-IDF method for the convenience of readers to read and understand. In situations where accuracy requirements are not very high, TF-IDF is sufficient for the tasks in this article. In addition, why don't you speak Chinese?

**Comment by YueYongDev** [comment]
> The lexicon of the two articles is too small, so the frequency values in the tfidf matrix calculated by this very very small corpus are not suitable for simple cosine similarity metrics, that is, they cannot reflect the similarity of the two articles in the field of performance culture. It will also be limited by the inevitable domain-specific words in the two papers themselves. (In fact, I tend to use my own built-in stop word list in any professional field). You can try to add a few papers after tf-idf and then look at the similarities between the two articles.

In this article, I only use the TF-IDF method for the convenience of readers to read and understand. In situations where accuracy requirements are not very high, TF-IDF is sufficient for the tasks in this article. In addition, why don't you speak Chinese?

**Comment by xiazl5515** [comment]
Hi Liang，because I need to practice writing my graduation thesis recently .They said I should not use Google Trans too often.NIDONGDE ^_^
